# Generated by Django 4.2.6 on 2023-10-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_author",
                to="posts.author",
            ),
            preserve_default=False,
        ),
    ]
